pipeline {
    agent { node { label 'terraform-node' } } 
    parameters {
                choice(name: 'Deployment_Type', choices:['apply','destroy'],description:'The deployment type')
                  }
    environment {
        EMAIL_TO = 'femithecoder@gmail.com'
    }
    stages {
        stage('1.Terraform init') {
            steps {
                dir('eksdeployproject/devopsprojectt/eks-terraform-deploy'){
                echo 'terraform init phase'
                sh 'terraform init'
                }
            }
        }
        stage('2.Terraform plan') {
            steps {
                dir('eksdeployproject/devopsprojectt/eks-terraform-deploy'){
                echo 'terraform plan phase'
                sh 'AWS_REGION=eu-west-2 terraform plan'
                }
            }
        }
        stage('3.Manual Approval') {
            input {
                message "Should we proceed?"
                ok "Yes, we should."
                parameters{
                    choice (name: 'Manual_Approval', choices: ['Approve','Reject'], description: 'Approve or Reject the deployment')
                }
            }
             steps {
                echo "Deployment ${Manual_Approval}"
            }          
        }
        stage('4.Terraform Deploy') {              
            steps { 
                dir('eksdeployproject/devopsprojectt/eks-terraform-deploy'){
                echo 'Terraform ${params.Deployment_Type} phase'  
                sh 'chmod +x scripts/update-kubeconfig.sh'
                sh 'ls -l scripts/update-kubeconfig.sh'  
                sh "AWS_REGION=eu-west-2 terraform ${params.Deployment_Type} --auto-approve"
                sh("""scripts/update-kubeconfig.sh""")       
                }            
                }
                }
        stage ('5. Email Notification') {
            steps {
                script {
                try {
                       mail bcc: 'bolarinwaibrahimo@gmail.com', 
                       cc: 'lawalolorunfemi@gmail.com',
                       body: '''Terraform deployment is completed.
                        Let me know if the changes look okay.
                        Thanks,
                        Domain System Technologies,
                        +447887768539''', 
                        from: 'femithecoder@gmail.com', 
                        replyTo: '', 
                        subject: 'Terraform Infra deployment completed!!!', 
                        to: 'olorunfemilawal007@gmail.com'
                          
               }  
               catch (Exception e) {
                        echo "Failed to send email notification: ${e}"
               }  
            }
          }
        } 
     }       
} 