pipeline {
    agent { node { label 'terraform-node' } } 
    parameters {
                choice(name: 'Deployment_Type', choices:['apply','destroy'],description:'The deployment type')
                  }
    environment {
        EMAIL_TO = 'olorunfemilawal47@gmail.com'
    }
    stages {
        stage('1.Terraform init') {
            steps {
                dir('eksdeployproject/devopsprojectt/eks-terraform-deploy')
                echo 'terraform init phase'
                sh 'terraform init'
            }
        }
        stage('2.Terraform plan') {
            steps {
                dir('eksdeployproject/devopsprojectt/eks-terraform-deploy')
                echo 'terraform plan phase'
                sh 'AWS_REGION=eu-west-2 terraform plan'
            }
        }
        stage('3.Manual Approval') {
            input {
                message "Should we proceed?"
                ok "Yes, we should."
                parameters{
                    choice (name: 'Manual_Approval', choices: ['Approve','Reject'], description: 'Approve or Reject the deployment')
                }
            }
             steps {
                echo "Deployment ${Manual_Approval}"
            }          
        }
        stage('4.Terraform Deploy') {              
            steps {
                dir('eksdeployproject/devopsprojectt/eks-terraform-deploy') 
                echo 'Terraform ${params.Deployment_Type} phase'  
                sh "AWS_REGION=eu-west-2 terraform ${params.Deployment_Type} --auto-approve"
                sh("""scripts/update-kubeconfig.sh""")
                sh("""scripts/install_helm.sh""") 
                }
                }
        stage ('5. Email Notification') {
            steps {
               mail bcc: 'olorunfemilawal47@gmail.com', body: '''Terraform deployment is completed.
               Let me know if the changes look okay.
               Thanks,
               Dominion System Technologies,
              +1 (313) 413-1477''', cc: 'olorunfemilawal47@gmail.com', from: '', replyTo: '', subject: 'Terraform Infra deployment completed!!!', to: 'olorunfemilawal47@gmail.com'
                          
               }    
          }
     }       
} 
